theme: minima
title: Welcome, stranger!
author: MStatkov
email: your-email@domain.com
description: first github page

# social links
github_username:  MStatkov # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
